version: 0.2

# AWS CodeBuild用のビルド仕様
# MAS HTTPサーバー＆メッセージングシステムのCI/CDパイプライン

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y tmux curl bc jq

      # Node.js依存関係（もしpackage.jsonがある場合）
      # - npm install

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Checking environment..."
      - node --version
      - tmux -V
      - curl --version

      # 環境変数の設定
      - export MAS_HTTP_PORT=8765
      - export MAS_TEST_MODE=ci

      # テスト用ディレクトリの作成
      - mkdir -p unit
      - mkdir -p tests/results

  build:
    commands:
      - echo "Build phase started on `date`"

      # MASシステムの起動
      - echo "Starting MAS system..."
      - tmux new-session -d -s mas-tmux

      # HTTPサーバーの起動
      - echo "Starting HTTP server..."
      - nohup node http_server.js > http_server.log 2>&1 &
      - export HTTP_PID=$!
      - sleep 2

      # サーバー起動確認
      - |
        for i in {1..10}; do
          if curl -s http://localhost:8765 > /dev/null 2>&1; then
            echo "HTTP server is running"
            break
          fi
          echo "Waiting for server to start... ($i/10)"
          sleep 1
        done

      # テスト実行
      - echo "Running test suites..."

      # 1. HTTPサーバーテスト
      - |
        echo "=== HTTP Server Tests ==="
        bash tests/test_http_server.sh > tests/results/http_server.log 2>&1
        HTTP_TEST_EXIT=$?
        cat tests/results/http_server.log

      # 2. 基本的な統合テスト
      - |
        echo "=== Integration Tests ==="
        # 簡易E2Eテスト
        curl -X POST http://localhost:8765/message \
          -H "Content-Type: application/json" \
          -d '{"target":"00","message":"CI test"}' \
          > tests/results/integration.log 2>&1
        INTEGRATION_EXIT=$?

      # 3. パフォーマンステスト（簡易版）
      - |
        echo "=== Performance Tests ==="
        START_TIME=$(date +%s)
        for i in {1..100}; do
          curl -s -X POST http://localhost:8765/message \
            -H "Content-Type: application/json" \
            -d '{"target":"00","message":"perf test"}' \
            -o /dev/null 2>&1
        done
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "100 requests completed in ${DURATION} seconds"
        echo "Average: $((DURATION * 10)) ms per request"

        # パフォーマンス基準チェック（平均100ms以下）
        if [ $((DURATION * 10)) -gt 100 ]; then
          echo "Performance test failed: Average response time > 100ms"
          exit 1
        fi

      # テスト結果の集計
      - |
        echo "=== Test Summary ==="
        TOTAL_FAILURES=0

        if [ $HTTP_TEST_EXIT -ne 0 ]; then
          echo "❌ HTTP Server tests failed"
          TOTAL_FAILURES=$((TOTAL_FAILURES + 1))
        else
          echo "✅ HTTP Server tests passed"
        fi

        if [ $INTEGRATION_EXIT -ne 0 ]; then
          echo "❌ Integration tests failed"
          TOTAL_FAILURES=$((TOTAL_FAILURES + 1))
        else
          echo "✅ Integration tests passed"
        fi

        if [ $TOTAL_FAILURES -gt 0 ]; then
          echo "Build failed with $TOTAL_FAILURES test failures"
          exit 1
        fi

        echo "All tests passed successfully!"

  post_build:
    commands:
      - echo "Post-build phase started on `date`"

      # テスト結果の保存
      - |
        if [ -f tests/results/http_server.log ]; then
          echo "Archiving test results..."
        fi

      # クリーンアップ
      - |
        if [ ! -z "$HTTP_PID" ]; then
          kill $HTTP_PID 2>/dev/null || true
        fi
        tmux kill-session -t mas-tmux 2>/dev/null || true

      # ビルド成功時の処理
      - echo "Build completed successfully"

      # デプロイ用のアーティファクト準備（必要に応じて）
      # - zip -r mas-tmux.zip . -x "*.git*" -x "tests/*" -x "*.log"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'tests/results/**/*'

  # テスト結果レポート
  secondary-artifacts:
    TestReports:
      files:
        - 'tests/results/**/*'
      name: test-reports

reports:
  # CodeBuildのテストレポート機能を使用
  TestResults:
    files:
      - 'tests/results/*.log'
    file-format: 'NONE'  # カスタムフォーマット

cache:
  paths:
    - '/root/.npm/**/*'  # npm cache
    - 'node_modules/**/*'  # 依存関係キャッシュ